=== lili-wu/documents-structures/exercices/livre.dtd
<!-- Lili WU -->
<!-- DTD pour structurer un livre -->

<!ELEMENT livre (titre,auteur,traducteur?,pays,genre,editeur,parution,serie,resume)>
    <!ATTLIST livre version CDATA #IMPLIED>

    <!ELEMENT titre (#PCDATA)>
    <!ELEMENT auteur (#PCDATA)>
    <!ELEMENT traducteur (#PCDATA)>
    <!ELEMENT pays (#PCDATA)>
    <!ELEMENT genre (#PCDATA)>
    <!ELEMENT editeur (#PCDATA)>
    <!ELEMENT parution (#PCDATA)>
        <!ATTLIST parution lieu CDATA #REQUIRED>
        <!ATTLIST parution date CDATA #REQUIRED>
    <!ELEMENT serie (pages,ISBN)>
        <!ATTLIST serie tome CDATA #IMPLIED>
        <!ELEMENT pages EMPTY>
            <!ATTLIST pages n CDATA #REQUIRED>
        <!ELEMENT ISBN (#PCDATA)>
    <!ELEMENT resume (p+)>
        <!ELEMENT p (#PCDATA)>

=== lili-wu/documents-structures/devoirs/livre.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!-- Lili WU -->
<!DOCTYPE bibliographie SYSTEM "livre.dtd">
<livre version="fr">
    <titre>Harry Potter à l'école des sorciers</titre>
    <auteur>J.K Rowling</auteur>
    <traducteur>Jean-François Ménard</traducteur>
    <pays>Royaume-Uni</pays>
    <genre>fantasy</genre>
    <editeur>Gallimard Jeunesse</editeur>
    <parution lieu="Paris" date="1998"/>
    <serie tome="1">
        <pages n="322"/>
        <ISBN>0747532699</ISBN>
    </serie>
    <resume>
        <p>Harry Potter à l'école des sorciers (titre original : Harry Potter and the Philosopher's Stone) est le premier roman de la série littéraire centrée sur le personnage de Harry Potter créé par J. K. Rowling. Sorti le 26 juin 19972, il est initialement tiré à 500 exemplaires. En France, le roman a été publié le 9 octobre 19981.</p>
        <p>Il trouve son importance puisqu'il sert de base introductive aux six autres tomes de la série ainsi qu'à la pièce de théâtre Harry Potter et l'Enfant maudit. Il permet à l'auteur de mettre en place l'univers, de familiariser le lecteur avec ses personnages, les lieux, les objets magiques, les mœurs et tout le vocabulaire propre à son monde. Ce premier tome installe progressivement les nœuds de l'intrigue grâce à des indices dissimulés pour ne pas éveiller les soupçons du lecteur dès le début de l'histoire.</p>
    </resume>
</livre>
